// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq9GRyztHfbDfnLaV_KKVfoPk5dqKb_C8',
    appId: '1:1062598222598:android:a0c6f5797242ee7675f487',
    messagingSenderId: '1062598222598',
    projectId: 'sniperpro-eaa57',
    storageBucket: 'sniperpro-eaa57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7jRqWvEgm_MmBKCeaGoIxuz5xjRQFpX8',
    appId: '1:1062598222598:ios:1978ae98bebd81b975f487',
    messagingSenderId: '1062598222598',
    projectId: 'sniperpro-eaa57',
    storageBucket: 'sniperpro-eaa57.appspot.com',
    iosBundleId: 'com.example.sniperPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7jRqWvEgm_MmBKCeaGoIxuz5xjRQFpX8',
    appId: '1:1062598222598:ios:984547314a2dbe7475f487',
    messagingSenderId: '1062598222598',
    projectId: 'sniperpro-eaa57',
    storageBucket: 'sniperpro-eaa57.appspot.com',
    iosBundleId: 'com.example.sniperPro.RunnerTests',
  );
}
