// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxm7mi861SEX6b9ed9uQOu_O7qaI_U9Bg',
    appId: '1:814536037544:android:c122673afe044a1e879e9d',
    messagingSenderId: '814536037544',
    projectId: 'sniperpro-a9151',
    databaseURL: 'https://sniperpro-a9151-default-rtdb.firebaseio.com',
    storageBucket: 'sniperpro-a9151.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXAvMiowBJmXqRkRKEMh3CwGvnaL1y5qI',
    appId: '1:814536037544:ios:91832d8bfae0796e879e9d',
    messagingSenderId: '814536037544',
    projectId: 'sniperpro-a9151',
    databaseURL: 'https://sniperpro-a9151-default-rtdb.firebaseio.com',
    storageBucket: 'sniperpro-a9151.appspot.com',
    iosBundleId: 'com.example.sniperPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXAvMiowBJmXqRkRKEMh3CwGvnaL1y5qI',
    appId: '1:814536037544:ios:5c24dd973536feba879e9d',
    messagingSenderId: '814536037544',
    projectId: 'sniperpro-a9151',
    databaseURL: 'https://sniperpro-a9151-default-rtdb.firebaseio.com',
    storageBucket: 'sniperpro-a9151.appspot.com',
    iosBundleId: 'com.example.sniperPro.RunnerTests',
  );
}
